Mentoring t 111
BI-kotlin-in-action-2ND/HeejuneKim pull request #1
Opened 2024-01-23 05:15 UTC by Heejun-0219

안녕하세요.

코틀린 스터디 2주 차
알고리즘 2문제 풀어서 제출하겠습니다.

cpp로만 문제를 풀다 보니 좀 알고리즘 문제를 풀 때, 코트린 언어로 생각하는 게 어려워서 이번주는 조금 쉬운 문제들로 골랐습니다.
리뷰 부탁드립니다.

감사합니다.

2024-01-23 13:24 UTC, konempty requested changes
크 고생하셨습니다 👍 👍 
요 정도만 하셔도 초보자 치곤 잘하시는 코드라고 생각이 드네요 ㅋㅋㅋ
대신 한가지 추가 조언 드리고 싶은게
gradle파일이나 기타 프로젝트 설정 파일은 PR에 포함 시키지 않고
레포지토리 init커밋으로 넣어두는게 국룰이고 예의(?)입니다 ㅋㅋㅋ

조금만더 코드를 손보면 좋을것 같아서 리뷰 수정후 다시 재 리뷰 요청 주세요~!

2024-01-23 13:24 UTC, konempty commented on src/main/kotlin/kr/bi/15649.kt
> +    val m = s[1].toInt()
요 경우 아래와 같이 코틀린에서는 압축이 가능합니다~!
```kotlin
val (n, m) = readln().split(' ')
```

2024-01-23 13:24 UTC, konempty commented on src/main/kotlin/kr/bi/15649.kt
> +    val arr = Array(m) { 0 }
숫자를 담는 배열의 경우 IntArray를 사용하면되구요 
IntArray는 기본적으로 모든 엘리먼트를 0으로 초기화 해주니까 더 좋습니다~!
```kotlin
val arr = IntArray(m)
```

2024-01-23 13:24 UTC, konempty commented on src/main/kotlin/kr/bi/15649.kt
> +    val visited = Array(n) { false }
여기도 BooleanArray를 쓰면 더 좋구요
엘리먼트의 기본값은 false입니다~!

2024-01-23 13:24 UTC, konempty commented on src/main/kotlin/kr/bi/15649.kt
> +    val sb = StringBuilder()
ㅋㅋㅋㅋ 요거 아마 성능때문에 그냥 스트링이 아닌 스트링 빌더를 쓰시는것 같은데
자바 6,7 까진 잘하신 코드인데
JDK 8인가 9부터는 동적 바인딩을 통해 String +연산도 자동으로 StringBuilder를 통한 연산으로 치환됩니다~!

추가)
https://howtodoinjava.com/java/string/string-concatenation-performance/#2-compiler-optimization-for-string-concatenation
바이트 코드까지 분석하는 블로그라 이해에 도움이 될것 같아요!

2024-01-23 13:24 UTC, konempty commented on src/main/kotlin/kr/bi/15649.kt
> +        with(sb) {
오호.. with를 쓰신 이유가 궁금합니다!

2024-01-23 13:24 UTC, konempty commented on src/main/kotlin/kr/bi/24060.kt
> +    val k = s[1].toInt()
요기도 코드 압축이 가능할것 같네요~!

2024-01-23 13:24 UTC, konempty commented on src/main/kotlin/kr/bi/24060.kt
> +        var (i, j, t) = listOf(p, mid + 1, 0)
어 뭐야 여기는 잘쓰셨네요 ㅋㅋㅋㅋㅋ

2024-01-23 13:24 UTC, konempty commented on src/main/kotlin/kr/bi/24060.kt
> +    val tmp = Array(n) { 0 } // 임시 배열 재사용
요기도 IntArray를 쓰시면 좋을것 같습니다~!

2024-01-23 13:24 UTC, konempty commented on src/main/kotlin/kr/bi/24060.kt
> +    ) {
요건 갠취이긴 한데
저는 함수 내부에서 함수를 구현하면 읽기가 어렵더라구요 ㅋㅋㅋㅋ..

2024-01-23 13:26 UTC, konempty commented
아 그리고 추가로 첨언드릴게 있는데
PR제목은 PR의 내용을 잘 나타낼수 있는 제목으로 바꿔주세요~!
[Mentoring t 111](https://github.com/BI-kotlin-in-action-2ND/HeejuneKim/pull/1#top)은 PR을 잘 설명해주지 못하네요 ㅋㅋㅋ

2024-01-24 14:33 UTC, Heejun-0219 commented on src/main/kotlin/kr/bi/15649.kt
> +    val m = s[1].toInt()
```kotlin 
val (n, m) = readln().split(' ').map { it.toInt() } 
```
다음과 같이 수정해보았습니다!

2024-01-24 14:34 UTC, Heejun-0219 commented on src/main/kotlin/kr/bi/15649.kt
> +    val arr = Array(m) { 0 }
모든 원소를 0으로 초기화해 준다는 사실은 몰랐습니다
```kotlin
    val arr = IntArray(m)
```

2024-01-24 14:37 UTC, Heejun-0219 commented on src/main/kotlin/kr/bi/15649.kt
> +    val visited = Array(n) { false }
```kotlin
    val visited = BooleanArray(n)
```
백준에서 해당 코드를 돌려봤을 때, cpp에 비해서 메모리 사용량이 훨씬 더 많더라고요. 알고리즘 문제를 풀 때, 메모리를 줄일 수 있는 컬렉션이나 자료구조가 따로 있는지 궁금합니다!

2024-01-24 14:41 UTC, Heejun-0219 commented on src/main/kotlin/kr/bi/15649.kt
> +    val sb = StringBuilder()
```kotlin
var result = ""
```
그럼 6장에서 배우는 BuildString도 잘 사용이 안 되나요?

2024-01-24 14:47 UTC, Heejun-0219 commented on src/main/kotlin/kr/bi/15649.kt
> +        with(sb) {
`sb.append()`를 반복적으로 사용하는 것보다 가독성이 좋지 않을까 생각해서 사용했습니다. 
근데, it과 같이 사용해서 더 코드가 복잡해지면 가독성이 오히려 떨어질 수도 있을 거 같습니다.

2024-01-24 14:48 UTC, Heejun-0219 commented on src/main/kotlin/kr/bi/24060.kt
> +    val k = s[1].toInt()
n, k를 최상위 프로퍼티로 변경하고 압축해봤습니다.

2024-01-24 14:49 UTC, Heejun-0219 commented on src/main/kotlin/kr/bi/24060.kt
> +        var (i, j, t) = listOf(p, mid + 1, 0)
3개를 선언하다 보니... 구글링의 힘을 좀 빌려봤습니다 하핳,,,

2024-01-24 14:51 UTC, Heejun-0219 commented on src/main/kotlin/kr/bi/24060.kt
> +    val tmp = Array(n) { 0 } // 임시 배열 재사용
```kotlin
lateinit var tmp: IntArray
```

이번 6장에서 배운 지연 초기화 키워드를 사용해서 최상위 프로퍼티(?)로 변경해봤습니다.

2024-01-24 14:51 UTC, konempty commented
<img width="315" alt="스크린샷 2024-01-24 오후 11 50 31" src="https://github.com/BI-kotlin-in-action-2ND/HeejuneKim/assets/44064530/79fb9cc6-c43d-4e8e-86d3-92252ceffb82">

리뷰 반영 안하시나 궁금해서 보러 오니까 리뷰 재 요청을 안주셨네요 ㅠㅠ
재 요청 버튼을 누르지 않으면 저한테 알림이 오지않아 제가 언제 리뷰를 해도 될지 알수가 없습니다

2024-01-24 14:52 UTC, Heejun-0219 commented
지금 수정하느라,... 밤 늦게 죄송합니다..

2024-01-24 14:52 UTC, konempty commented on src/main/kotlin/kr/bi/15649.kt
> +    val visited = Array(n) { false }
ㅋㅋㅋㅋ 그건 자바인이상 CPP만큼 메모리 소모를 줄일수는 없네요
그리고 메모리 제한은 네카라쿠배 코테정도까지는 전혀 문제가 되지않아요!

2024-01-24 14:53 UTC, konempty commented on src/main/kotlin/kr/bi/15649.kt
> +    val sb = StringBuilder()
그건 갠취이긴한데 저는 가끔 사용합니다~!

2024-01-24 14:53 UTC, konempty commented
아하 그러면 다 수정하시면 리뷰 재 요청주세요~!

2024-01-24 14:54 UTC, Heejun-0219 commented on src/main/kotlin/kr/bi/24060.kt
> +    ) {
뭔가 함수 내부에 쓰지 않으면, 배열을 들고 다녀야 해서 그렇게 구현하는 것보다는 낫지 않을까 생각했습니다.
해당 부분은 최상위 프로퍼티로 배열 컬렉션을 변경했습니다. 전역변수처럼 사용하는 것이 코틀린스러울지가 궁금합니다

2024-01-24 14:54 UTC, Heejun-0219 commented
지금 막 다해서 요청드렸습니다!

2024-01-24 14:55 UTC, Heejun-0219 commented on src/main/kotlin/kr/bi/15649.kt
> +    val visited = Array(n) { false }
아하 감사합니다

2024-01-24 15:02 UTC, konempty approved these changes
요번주 내용은 기초적인 문법만 활용하신것 같아서
리뷰가 많지는 않았지만 다음번 부터는 좀더 많은 리뷰를 드릴수 있을것 같으니
기대해주세요!

너무 고생 많으셨구요
리뷰 하나만 반영하신뒤 머지하셔도 좋습니다!

그리고 다른 분들은 어떤 리뷰를 받았는지 보시고 미리 숙지해두시면
앞으로 리뷰받으실때 도움이 될것 같습니다~!

2024-01-24 15:02 UTC, konempty commented on src/main/kotlin/kr/bi/24060.kt
> +    a = readln().split(' ').map { it.toInt() }.toTypedArray()
엇 아마 toTypedArray 대신에 toIntArray를 사용할수 있을거예요..!

2024-01-24 15:04 UTC, konempty commented on src/main/kotlin/kr/bi/24060.kt
> +    ) {
그건 취향의 영역이라
전역변수를 많이 활용하는게 코틀린 스러움이다 VS 객체지향 원칙을 어느정도 지켜야 코틀린스럽다
요런 싸움이 있긴해요 ㅋㅋㅋ

2024-01-24 15:04 UTC, konempty commented on src/main/kotlin/kr/bi/24060.kt
> +    val tmp = Array(n) { 0 } // 임시 배열 재사용
넵 좋습니다~!

2024-01-24 15:04 UTC, konempty commented on src/main/kotlin/kr/bi/24060.kt
> +        var (i, j, t) = listOf(p, mid + 1, 0)
ㅋㅋㅋㅋㅋ

2024-01-24 15:06 UTC, konempty commented on src/main/kotlin/kr/bi/15649.kt
> +        with(sb) {
with와 같은 역할로 하는 문법으로
run, let, apply, also 요 4개가 있는데 그것들의 차이점과 어떨때 쓰는지 알아보시면
이때 어떤게 더 어울렸을것 같은지 아실수 있을거라고 믿습니다!

![image](https://github.com/BI-kotlin-in-action-2ND/HeejuneKim/assets/44064530/b1c4d33e-e7aa-43be-a541-576de75911ef)

2024-01-24 15:17 UTC, Heejun-0219 commented on src/main/kotlin/kr/bi/24060.kt
> +    a = readln().split(' ').map { it.toInt() }.toTypedArray()
해당 부분도 고쳤습니다! 감사합니다
앞으로도 잘부탁드립니다!

2024-01-24 15:18 UTC, merged